name: Mailing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
  
      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_port: 465
          secure: true
          ignore_cert: false
          subject: ${{ github.repository }} Job result
          to: wclin@nuvoton.com
          cc: chhsieh3@nuvoton.com
          bcc: wclin@nuvoton.com
          from: Wayne Lin <your_email@example.com>
          #attachments: ${{ steps.prepare_logs.outputs.logs }}
          body: |
            Hello,

            The build has completed. Please find the attached log file for details.

            Regards,
            NuMicro Actions

