name: Mailing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
  
      - name: Send mail
        uses: dawidd6/action-send-mail@v5
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: ${{github.repository}} Job result
          to: wclin@nuvoton.com
          from: Wayne Lin # <user@example.com>
          body: |
            Hello,
 
            The build has completed. Please find the attached log file for details.
  
            Regards,
            NuMicro Actions          # Optional carbon copy recipients:
          cc: chhsieh3@nuvoton.com
          bcc: wclin@nuvoton.com
          #attachments: ${{ steps.prepare_logs.outputs.logs }}
